###
@categoryId = {{ createCategory.response.body.id}}
###
@taskId = {{ createTask.response.body.id}}

###
@authenticate = {{ authenticate.response.body.accessToken }}


###
# @name createCategory
POST http://localhost:8080/categories
content-type: application/json
Authorization: Bearer {{ authenticate.response.body.accessToken }}


{
  "name": "Teste",
}

###
GET http://localhost:8080/categories
Authorization: Bearer {{ authenticate.response.body.accessToken }}


###
GET http://localhost:8080/categories/{{categoryId}}
Authorization: Bearer {{ authenticate.response.body.accessToken }}



###
# @name createTask
POST http://localhost:8080/tasks
content-type: application/json
Authorization: Bearer {{ authenticate.response.body.accessToken }}

{
  "name": "Limpar a Casa",
  "description": "Não se esqueça de lavar a louça",
  "categoryId": 1,
  "userId": 1
}


###
GET http://localhost:8080/tasks/{{taskId}}
Authorization: Bearer {{ authenticate.response.body.accessToken }}


###
GET http://localhost:8080/tasks
Authorization: Bearer {{ authenticate.response.body.accessToken }}


###
GET http://localhost:8080/tasks?done=true
Authorization: Bearer {{ authenticate.response.body.accessToken }}


###
GET http://localhost:8080/tasks?done=false
Authorization: Bearer {{ authenticate.response.body.accessToken }}


###
PUT http://localhost:8080/tasks/{{taskId}}/done
Authorization: Bearer {{ authenticate.response.body.accessToken }}


###
PUT http://localhost:8080/tasks/{{taskId}}/undone
Authorization: Bearer {{ authenticate.response.body.accessToken }}


###
GET http://localhost:8080/users

###
POST http://localhost:8080/users
content-type: application/json

{
  "name": "João",
  "email": "joao@email.com",
  "password": "123456",
  "username": "joao"
}

###
# @name authenticate
POST http://localhost:8080/login
Content-Type: application/json

{
  "username": "joao",
  "password": "123456"
}


###
POST http://localhost:8080/login
Content-Type: application/json

{
  "username": "juancassiano",
  "password": "password"
}

###
GET http://localhost:8080/categories/test
Authorization: Bearer {{ authenticate.response.body.accessToken }}
