version: "3.9"

services:
  db:
    image: mysql:8.0.30-debian
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: ""
    ports:
      - "3306:3306"
    volumes:
      - ./.docker/mysql:/docker-entrypoint-initdb.d
